[package]
name = "tfl-lab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bnf = "0.5.0"
ndarray = "0.15.6"
once_cell = "1.19.0"
rand = "0.8.5"
